# Generated by Django 5.2.6 on 2025-09-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.DateTimeField(auto_now_add=True)),
                ('cpu', models.FloatField()),
                ('memory', models.FloatField()),
                ('disk', models.FloatField()),
            ],
        ),
    ]
