# Generated by Django 5.2.6 on 2025-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField()),
                ('timing', models.DateTimeField(auto_now_add=True)),
                ('cpu', models.FloatField()),
                ('memory', models.FloatField()),
                ('disk', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='records',
        ),
    ]
