# Generated by Django 5.2.6 on 2025-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0002_record_delete_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_instance', models.CharField()),
                ('metric_type', models.CharField()),
                ('threshold', models.FloatField()),
                ('value', models.FloatField()),
                ('trigger_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
