# Generated by Django 5.2.6 on 2025-10-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0003_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='threshold',
        ),
    ]
