# Generated by Django 5.2.6 on 2025-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0004_remove_alert_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_instance', models.CharField()),
                ('cpu_threshold', models.FloatField()),
                ('memory_threshold', models.FloatField()),
                ('disk_threshold', models.FloatField()),
                ('recipients', models.JSONField(default=list)),
            ],
        ),
    ]
