# Generated by Django 5.2.17 on 2026-08-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0005_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='metric_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='server_instance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='instance_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='server_instance',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
